# Generated by Django 4.2.2 on 2023-07-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='Fecha_Nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='Lugar_De_Nacimiento',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
