# Generated by Django 4.2.2 on 2023-07-30 22:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_persona_fecha_nacimiento_persona_lugar_de_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
