# Generated by Django 4.2.2 on 2023-07-31 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_persona_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='user',
        ),
    ]
