# Generated by Django 4.2.2 on 2023-07-31 22:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0009_infoextra_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoExtra_Usuario',
            new_name='InfoExtra_Persona',
        ),
    ]
