# Generated by Django 4.2.2 on 2023-07-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_rename_infoextra_usuario_infoextra_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.DeleteModel(
            name='InfoExtra_Persona',
        ),
    ]
