# Generated by Django 4.2.2 on 2023-07-31 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_proveedor_avatar_delete_infoextra_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='avatar',
            new_name='avatarProve',
        ),
    ]
